### PR TITLE
Added 2-Legged OAuth client support 

### PR DESCRIPTION
**Pull request by ramv**
Ciaranj, as requested in  issue 21 https://github.com/ciaranj/connect-auth/issues/#issue/21 I have implemented 2-legged OAuth support and made sure that both 3-legged and 2-legged versions work. Please review.

### CODE REVIEW

**Comment by ciaranj** [comment]
I think you may be missing files in that commit, it appears to just be some examples ATM ?

**Comment by ramv** [comment]
oops. Yes .. sorry my first time using Git. I am an svn user and thought if I did git commit then even modified changes are committed  :). Fixed now.

**Comment by ramv** [comment]
any update on the pull request?

**Comment by ramv** [comment]
Hi Ciaranj,
Happy New Year
can I get an update on the pull request please?

**Comment by ciaranj** [comment]
Hiyah, I've not forgotten it, I'm very interested in the pull.  I scanned the commits, and decided I wanted to spend some time carefully reviewing it.  Its the very next thing on my OSS list of things to do <g>  Happy new year to you too.

**Comment by ramv** [comment]
Hey Ciaranj,
any update?

**Comment by agad** [comment]
Any update on this?  I am actually looking for a 2legged provider.  Ramv, have you used this patch in production?

**Comment by ramv** [comment]
Yes I have.

**Comment by xentac** [comment]
I am interested in this as well.  Is there anything we can do to help move this along?  As it stands, if I want to use this, it seems like I'd have to port the changes to the most recent version.

**Comment by ciaranj** [comment]
Hmmm, I'm surprised that this pull request is listed as being able to automatically merge, when I first reviewed it the scale of the changes (whitespace etc.) looked a bit too much for me to safely review... if someone else could spare some time to do the merge on a local branch and test it that would very much speed-it-along!

**Comment by xentac** [comment]
Ok, I'll spend today looking at the patches (though the oauth strategy hasn't really been changed for a while).  Perhaps I can clean them up a bit so they're more acceptable :)

**Comment by ciaranj** [comment]
That would be most awesome of you :)

**Comment by xentac** [comment]
Not sure where else I should link this from.  Here is the pull request: https://github.com/ciaranj/connect-auth/pull/76

**Comment by ciaranj** [comment]
;) Don't worry my inbox lit up like a christmas tree, thank you I'll take a look at the earliest opportunity (sometime during tomorrow I would think)

**Comment by ciaranj** [comment]
Hey there, I've now merged xentac's variant on the 2-legged OAuth provider, hopefully this fulfills your needs too ramv.

**Comment by ramv** [comment]
I will check it out Ciaran. Thanks!

On Wed, Feb 29, 2012 at 1:41 PM, Ciaran Jessup <
reply@reply.github.com

> wrote:
> 
> Hey there, I've now merged xentac's variant on the 2-legged OAuth
> provider, hopefully this fulfills your needs too ramv.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ciaranj/connect-auth/pull/22#issuecomment-4247417

## 

Best Regards,

Ram Viswanadha

**Pull request closed without merging**
