### PR TITLE
Facebook Auth Fixes

### PR DESCRIPTION
**Pull request by frostbytten**
Seem like a stable fix for the Facebook issue. May need to be applied to other OAuth2 strategies as well.

### CODE REVIEW

**Comment by ciaranj** [comment]
Cool, I'll take a look later, really I'd like to re-write all the Oauth + OAuth2 strategies to re-use code .. they've kinda happened organically!

**Comment by frostbytten** [comment]
I agree, I just really needed facebook-auth working for a national rollout. So I made a focus.

**Comment by ciaranj** [comment]
Oh yeah, sure wasn't a criticism, all help appreciated, I was mainly apologising ;)

**Comment by frostbytten** [comment]
No need. Glad I could help.

**Comment by franklywatson** [comment]
Hi Frostbytten...

I was just reading over this pull request as I was tinkering with trying to get the [Express Facebook example] (https://github.com/ciaranj/connect-auth/wiki/Express---Facebook-example-(with-additional-cunning-sign-in-page-redirect-logic\)) code working. 

It seemed to me as though you already have something working and I was wondering if there were any kind of updated examples of how you are presently using your forked connect-auth for OAuth with FB?

**Comment by frostbytten** [comment]
Try this: https://gist.github.com/1021439

**Comment by frostbytten** [comment]
Correction on above 'old habit'...

`Both s== undefined and s=== undefined comparisons will throw an error if s is an undeclared variable, 
while it is safe to use typeof s in that case.`

This is why it's an old habit to me.

**Comment by franklywatson** [comment]
Thanks for this.. Going to try it out now :)

**Comment by franklywatson** [comment]
It works - thanks that's a great starting point!

**Comment by frostbytten** [comment]
Thanks. Good to know. Please let me know either via this thread or on my repo if there are any bugs I need to fix. I would love to see this concept rolled out generically across all the strategies.

**Comment by ciaranj** [comment]
Hey dude, I've partially merged this into: https://github.com/ciaranj/connect-auth/tree/merging_facebook_fixes  and applied some (minor) changes on top of that.  Please could you take a look and see what you think (in particular take a look at the TODO)

**Comment by frostbytten** [comment]
I'll pull the changes into my app tonight for testing, but everything looks more consistent with the way the other modules work. You might want to check on the other OAuth2 strategies if they are having the same type of issue.

**Comment by ciaranj** [comment]
I think you're correct, the issue will 'always' have been there, I imagine connect has become more strict about 'post flush' header requests at some point.

Please be aware these changes are still subject-to-change, I'm not massively keen on passing back 'undefined' for the 'authenticated'  argument, but sensible alternatives require multiple callback functions to be declared which feels over-the-top :)

**Comment by ciaranj** [comment]
Implemented in 0.3.0

**Pull request closed without merging**
