### PR TITLE
Updated Google2 Authentication to use the Google UserInfo api

### PR DESCRIPTION
**Pull request by hmcqueen**
I had trouble getting the provided Google2 authentication to work.  Looking at Google's OAuth2 page, http://code.google.com/apis/accounts/docs/OAuth2Login.html, I noticed they have a new userinfo api for use with OAuth2 authentication.  The scope I included provides the user's email address.  If you add 'https://www.googleapis.com/auth/userinfo.profile', then you will also get the user's names, etc.

### CODE REVIEW

**Comment by ciaranj** [comment]
Oh wow, if they've finally sorted that out, life will be much easier!  (it was a royal pain previously grabbing the email!)  I'll take a look as soon as I've got a moment, thank you.

**Comment by hmcqueen** [comment]
I just remembered that this will require the update to node-oauth lib/_utils.js that added matching for googleapis.com

**Comment by ciaranj** [comment]
Thank you for submitting this pull request, unfortunately I (stupidly) forgot to merge it, then (in-advertently) re-implemented it myself in commit: 2e549558ec74d3affdb65146b0c13554077536de  

it is very similar to yours, except it includes profile by default, and you can opt to include e-mail. Hopefully my implementation will still suit your use-case ?

**Comment by hmcqueen** [comment]
No problem.  I had actually forgotten about it myself and gone ahead and used my fork to implement a new strategy I needed.

**Comment by ciaranj** [comment]
Cool, as long as you don't think I'm snubbing you ;)

**Pull request closed without merging**
