### PR TITLE
added connect and expresso as dependencies. Not having this is causing pr

### PR DESCRIPTION
**Pull request by c4milo**
added connect and expresso as dependencies. Not having this is causing problems with recent versions of npm.

### CODE REVIEW

**Comment by ciaranj** [comment]
Cheers! This was confusing a number of people!

**Comment by c4milo** [comment]
hey thanks for applying this patch, would you mind please to upload a new version to the npm registry?

**Comment by ciaranj** [comment]
I will do as soon as I've reviewed the outstanding stuff (want to get in the OAuth2/Facebook fixes first) shouldn't be too long though :)

**Comment by c4milo** [comment]
sounds good, thank you.

**Pull request merged**
