### PR TITLE
OAuth2 support for google and Bitbucket support

### PR DESCRIPTION
**Pull request by fjakobs**

### CODE REVIEW

**Comment by ciaranj** [comment]
Hey there 6f69b0e looks good (Thank you) .. but 1feb74a seems broken ??

**Comment by fjakobs** [comment]
It would be cool if you could cherry pick the bitbucket commit. This one is tested and will be integrated with Cloud9. The google code is currently not used by us and might be broken. I probably should not have included it in the pull request. I'll open a new one once we actually use google oauth and are confident that the code works.

**Comment by ciaranj** [comment]
I've cherry-picked in commit 6f69b0e and pushed back up to the github repo's master branch.  I'll close this request for now if thats ok ?

**Comment by fjakobs** [comment]
sure

**Pull request closed without merging**
