### PR TITLE
Included node-oauth as submodule

### PR DESCRIPTION
**Pull request by dz0ny**
I've also fixed paths

### CODE REVIEW

**Comment by ciaranj** [comment]
Yeah, I appreciate why you've done this (hadn't yet had time to comment on your earlier commit, only just got home.) But its kinda like that way deliberately atm :) 

My current development approach is to use npm for my projects so 'oauth' is already on the requires path, and people don't have to download more than they need to.  The Oauth is only a dependency for some of the strategies ... 

However ;) for the example strategy I might rely on the submodule  being there (as people using the example will likely have done a git clone (iff oauth isn't already on the requires.path) 

The neatest thing todo (imho) is to in the loading application put the submodule for node-oauth onto the requires.path in your entry-point .js ... really the submodule should be at the level of your app, not under a connect-auth sub folder.... what do you think ?

**Comment by ciaranj** [comment]
hey man, could you take a look at what I've done in http://github.com/ciaranj/connect-auth/commit/53f1cd3deea5d4b4147707e18e2ff80ed2f0e679  and let me know if you're happy with that .. I _think_ the approach should keep everyone happy, as the npm users will just be able to carry on with it 'just wokring' .. and people who wish to manage their modules specifically will just need to make sure that the submodule is on the require.paths array -wadda-ya-think ?

**Comment by dz0ny** [comment]
yeah, that's a way to do it. And there's another even better way that I actually borrowed from express, check out http://github.com/dz0ny/connect-auth/commit/11da2428113b4d073ef05213bc94e7fa22aee580, git submodules are great way for version dependency, just like bundler for ROR.

**Comment by ciaranj** [comment]
My commit was done using a submodule ?  The issue with the approach you've outlined there is it won't be compatible with the package manager.  I"m aiming for it to work transparently in both cases, which I _think_ http://github.com/ciaranj/connect-auth/commit/53f1cd3deea5d4b4147707e18e2ff80ed2f0e679 allows for ?

**Pull request closed without merging**
