### PR TITLE
Implemented nk.pl auth strategy

### PR DESCRIPTION
**Pull request by mrblur**
Implemented nk.pl's "Zaloguj z nk" oauth authentication, second biggest social networking site in Poland.
It uses oauth2 for authorization and oauth 1.0 for getting user's profile data.

### CODE REVIEW

**Comment by Zenedith** [comment]
Good job!

**Comment by ciaranj** [comment]
Hi, I'm going to merge this 'as is' into a branch called 'nk.pl' but I cannot test it successfully, would you mind taking a look at the branch 'nk.pl' and confirming that it works for you please?

**Comment by mrblur** [comment]
Hi,
I'm afraid I no longer work for nk.pl and thus I do not have required credentials for testing :(

I actually used this code for project and it worked. I believe that since nk.pl official github team forked my code you can use it for upstream bug hunting in case of problems ;)

Best regards,

## Kamil

Wysłane z Androida za pomocą K-9 Mail. Prosze wybaczyć lakoniczność.

Ciaran Jessup reply@reply.github.com napisał:

Hi, I'm going to merge this 'as is' into a branch called 'nk.pl' but I cannot test it successfully, would you mind taking a look at the branch 'nk.pl' and confirming that it works for you please?

---

**Comment by ciaranj** [comment]
Ah, ok Thank you.  @Zenedith any thoughts on this ?

**Comment by Zenedith** [comment]
I agree with Kamil.

**Comment by ciaranj** [comment]
I guess no-one cares for this, so closing (without merging) :(

**Pull request closed without merging**
